### ISSUE TITLE
Webapp Starting Screen

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#14]
Webapp should start you directly on the current "army books" screen. 
The rest should only be accessible via direct link (for now).

**Comment by schnick3rs** [comment]
@onepageanon do you mean this view: https://opr-list-builder.herokuapp.com/army-books ?

**Comment by onepageanon** [comment]
Yes, this view: https://opr-list-builder.herokuapp.com/army-books

**Comment by schnick3rs** [comment]
![image](https://user-images.githubusercontent.com/17150506/140829170-a17865a0-6544-47c4-bcfa-8e8f1c1890ea.png)
@onepageanon would this work for you?

**Comment by schnick3rs** [comment]
@onepageanon This is done for now right? I'm closing the issue.
