### ISSUE TITLE
Alien Hives - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#21]
https://opr-list-bui-feature-po-r8wmtp.herokuapp.com/army-books/view/w7qor7b2kuifcyvk/print

- [x] Psy-Barrier should be 15pts
- [x] Toxic Cysts (Poison in melee) should not be free
- [x] Venom Floaters cost is wrong
- [x] Shrouding Mist should be 45pts
- [x] Psychic Synapse should be 45pts
- [x] Spawn Brood should be 190pts
- [x] Spores (special rule) should be 25pts
- [x] Handle `Any model may replace one Razor Claws:` see #23 

![image](https://user-images.githubusercontent.com/17150506/136781050-8ef46112-b90a-4320-a71d-e20df147cacb.png)
![image](https://user-images.githubusercontent.com/17150506/136781097-26e91424-afb4-46f2-97cd-23985519b0db.png)

**Comment by schnick3rs** [comment]
![image](https://user-images.githubusercontent.com/17150506/136781000-888f8435-2c0f-4e1e-90c9-f68880edab1d.png)
