### ISSUE TITLE
Battle Brothers - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#22]
https://opr-list-bui-feature-po-r8wmtp.herokuapp.com/army-books/view/78qp9l5alslt6yj8/print

- [ ] Upgrade H replace with Hammers + Shields doesn't seem to have the correct cost
- [ ] Upgrade I replace all Heavy Pistols + CCWs doesn't seem to have the correct cost
- [x] Repair should be 25pts
- [x] Advanced Tactics should be 25pts
- [x] Fearless is currently 0pts?
- [ ] Check attachment costs?
- [ ] List B cost of Destroyer Armor wrong
- [x] War Chant should be 15pts
- [ ] Upgrade lists D, E and G seem to be mixed up
- [ ] List B2, laser cannon attachment shouldn't be free
- [ ] List B2, laser cannon + twin plasma combo won't let me put the plasma rifle attacks

![image](https://user-images.githubusercontent.com/17150506/136787510-c09896c2-b8ce-44be-9eb3-1f1d145fd0b8.png)

![image](https://user-images.githubusercontent.com/17150506/136787758-cefd8431-5893-4b20-8094-7937bedabe86.png)

**Comment by onepageanon** [comment]
Can't it be displayed anyway? It would be as simple as Tough*1pts for Q6+ to Q4+, and then Tough*2pts for Q3+, and then it's 0pts for Q2+.

**Comment by schnick3rs** [comment]
@onepageanon those are the rounded cost
![image](https://user-images.githubusercontent.com/17150506/136787810-21c4f53c-4b01-44e2-bfd2-5b18d876d7e4.png)

would you have expected +10pts for all attachments?

**Comment by schnick3rs** [comment]
@onepageanon regarding `List B cost of Destroyer Armor wrong` what is the expected cost?

**Comment by schnick3rs** [comment]
@onepageanon regarding `Energy Hammers (A3, Blast(3)), Combat Shields (Shield Wall)` might be due to the import. Can you remove the option and re add it?

Energy Hammers (A3, Blast(3)) [WEAPON]
Combat Shields (Shield Wall) [ITEM]

**Comment by schnick3rs** [comment]
@onepageanon regarding `Destroyer Armor (Ambush, Tough(+3))` might be due to import. Can you remove the option and add the item again?
