### ISSUE TITLE
"Explosive(X)" rule in Alien Hives 2.50 army list doesn't display in the printout.

### ISSUE THREAD

**Issue by Darguth** [schnick3rs/opr-web-companion#4]
Imported the `Explode(X)` rule fine using the data tool and it appears to exist in the WC list-builder UI:
![image](https://user-images.githubusercontent.com/8975633/135885832-d3e24c57-d751-4f90-909c-7bb01f81fffe.png)

But does not display in the generated PDF printout using the app:
![image](https://user-images.githubusercontent.com/8975633/135885976-9dc89ee2-15c5-405f-b35b-23d9911c330d.png)

**Comment by schnick3rs** [comment]
@Darguth i think the json format is maybe off.

Can you try to readd the rule in the WC (make sure to switch to `has rating` in the dialog) and see if its working then?

Can you get me the import JSON snippet (either the total OR the one for the exploded rule)?

**Comment by Darguth** [comment]
@schnick3rs You're right, it was a problem where the imported Army Special Rule:
1. Had `(X)` in the name, which it isn't supposed to do.
2. Didn't toggle the `Has Rating` flag.

I recreated the rule via the WC GUI and it's working as expected now. So it was just a problem with the generated .json. I can work around this for the 1-time migration from PDFs.
