### ISSUE TITLE
Dwarf Guilds - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#41]
https://opr-list-bui-feature-po-r8wmtp.herokuapp.com/army-books/view/fk1mkbp8apvltu0z/print

- [x] Berserk Veteran upgrade list is broken
![image](https://user-images.githubusercontent.com/17150506/139872610-7f7cb105-5842-4256-a005-267cc96439d7.png)

**Comment by schnick3rs** [comment]
@onepageanon i recalced (after another fix) and now its `+5pts` is this the expected cost? if so. Ticket can be closed

**Comment by JamJar152** [comment]
Extra Issues:

Miners have the "Replace one Rifle + CCW" option, but default equipment is Pistol and there is no option to change to a Rifle so the option is unusable/pointless See screenshot below

![image](https://user-images.githubusercontent.com/93403931/139958312-1782700a-becc-45f1-bb75-98508c4573f9.png)

Same issue as above for:
- Jetpack Warriors
- Dwarf Support

(Screenshots below for Jetpack Warriors + Dwarf Support)

![image](https://user-images.githubusercontent.com/93403931/139958396-902be38e-f1e0-4fde-ad4d-1eb5a4ab4436.png)

![image](https://user-images.githubusercontent.com/93403931/139958419-fdcdac91-fbd0-401f-b8c8-f53c0150cd17.png)

**Comment by onepageanon** [comment]
> Extra Issues:
> 
> Miners have the "Replace one Rifle + CCW" option, but default equipment is Pistol and there is no option to change to a Rifle so the option is unusable/pointless See screenshot below
> 
> ![image](https://user-images.githubusercontent.com/93403931/139958312-1782700a-becc-45f1-bb75-98508c4573f9.png)
> 
> Same issue as above for:
> 
> * Jetpack Warriors
> * Dwarf Support
> 
> (Screenshots below for Jetpack Warriors + Dwarf Support)
> 
> ![image](https://user-images.githubusercontent.com/93403931/139958396-902be38e-f1e0-4fde-ad4d-1eb5a4ab4436.png)
> 
> ![image](https://user-images.githubusercontent.com/93403931/139958419-fdcdac91-fbd0-401f-b8c8-f53c0150cd17.png)

the point is that you can replace the CCW :)
