### ISSUE TITLE
Elven Jesters - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#42]
https://opr-list-bui-feature-po-r8wmtp.herokuapp.com/army-books/view/nyh41t82jugcdq8m/print

- [x] Heavy Jetbike transport upgrade cost is wrong (should be 18pts as per new cost)
![image](https://user-images.githubusercontent.com/17150506/139873016-79944932-f6fb-4275-8a8b-8b11830d98ba.png)

**Comment by schnick3rs** [comment]
@onepageanon should be fixed
