### ISSUE TITLE
Havoc Brothers - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#43]
- [x] Leader Weapons, replacing a heavy pistol with plasma pistol should not be free
- [x] Chosen Veteran special rule should cost 20pts

**Comment by schnick3rs** [comment]
@onepageanon regarding
> Leader Weapons, replacing a heavy pistol with plasma pistol should not be free

Potential parser issue, please readd. Indicator: missing closing bracket in PDF view.
![image](https://user-images.githubusercontent.com/17150506/139870707-b3eb5d2d-742a-4e37-a62e-a920115241ab.png)

**Comment by schnick3rs** [comment]
@onepageanon 
> Chosen Veteran special rule should cost 20pts

fixed, please recalc
