### ISSUE TITLE
High Elf Fleets - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#44]
- [x] Anti-Gravity Tank upgrades are broken
- [x] Wraith Suit Squad upgrade "Energy Sword + Shield" might have the wrong cost (unclear)

**Comment by schnick3rs** [comment]
![image](https://user-images.githubusercontent.com/17150506/139666629-27bd6f8b-2c48-4c40-892f-9d68081142f5.png)

**Comment by schnick3rs** [comment]
Wraith upgrade is correct 

vanilla
![image](https://user-images.githubusercontent.com/17150506/139667055-8106e719-cbfd-4015-a936-37fd701d3175.png)


shield
![image](https://user-images.githubusercontent.com/17150506/139666962-9f3938c7-512f-4f91-9b01-363df87d3334.png)
