### ISSUE TITLE
Infected Colonies - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#46]
https://opr-list-bui-feature-po-r8wmtp.herokuapp.com/army-books/view/dnthspt7c0klhmt8/print

- [x] Great Hunter upgrade Hardened Claws is broken
- [x] Hunters upgrade Hardened Claws is broken

`Hardened Claws (AP(+2) in melee)`

**Comment by schnick3rs** [comment]
![image](https://user-images.githubusercontent.com/17150506/139806251-0e5ba8e1-095e-4ad2-a0e5-d322c12025d2.png)

![image](https://user-images.githubusercontent.com/17150506/139806465-be7e65fa-4bc4-44c5-8e95-1c9ef4170bd0.png)
