### ISSUE TITLE
Orc Marauders - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#48]
- [x] No Retreat on Goblins seems to return an incorrect cost (should be 10pts)

**Comment by AdamLay** [comment]
Upgrade section is incorrect - parsing issue
![image](https://user-images.githubusercontent.com/4223668/139600560-fdff60d5-1f9b-4554-8087-9d3feba3c031.png)

**Comment by onepageanon** [comment]
> Upgrade section is incorrect - parsing issue ![image](https://user-images.githubusercontent.com/4223668/139600560-fdff60d5-1f9b-4554-8087-9d3feba3c031.png)

Fixed
