### ISSUE TITLE
Titan Lords - Army Issue - Preceptor Titan Pulse Laser Range in wrong column

### ISSUE THREAD

**Issue by Darguth** [schnick3rs/opr-web-companion#57]
Reported in AF backlog as https://github.com/AdamLay/opr-army-forge/issues/159

The range shows up in the special rules section, with no tooltip.  

![Screenshot_20211102-074945_Chrome.jpg](https://user-images.githubusercontent.com/7913700/139840918-26cd118a-7ab2-4178-9192-9f08ffb52194.jpg)

**Comment by schnick3rs** [comment]
Seems fixed, closing.
@Darguth FYI
