### ISSUE TITLE
Dark Elf Raiders - Army Issues

### ISSUE THREAD

**Issue by JamJar152** [schnick3rs/opr-web-companion#59]
Dark Lord unit has "Replace one Barb Rifle + CCW" option, but default equipment is Barb Pistol so the option is unusable, also  there is no option to change to a Barb Rifle. See screenshot below

![image](https://user-images.githubusercontent.com/93403931/139954426-78a107bf-fdc0-4b06-be44-e1abd8961632.png)

Succubus has the same issue as above

![image](https://user-images.githubusercontent.com/93403931/139954577-8e56cb3c-85be-4ed2-bc41-b20f1e03fc14.png)

Witches unit has the same issue as above

![image](https://user-images.githubusercontent.com/93403931/139955389-b6f538ce-9b06-451f-be1a-6630f04834a1.png)

Winged Warriors have the same issue as above, with the addition of a "Replace one Barb Pistol" option that is also unusable as there is no option to get a "Barb Pistol" (Default equpiment is Barb Carbines)

![image](https://user-images.githubusercontent.com/93403931/139955701-c99a4281-7063-4daf-9ca9-b198f654737e.png)

Jetbike Riders have the same issue as the Dark Lord ("Replace one Barb Rifle + CCW" option but unusable), there is default equpiment of "Twin Barb Rifles" which might be intended for option to use?

![image](https://user-images.githubusercontent.com/93403931/139956007-3ff8f619-365f-4e5a-a535-d82790c44713.png)

**Comment by schnick3rs** [comment]
@JamJar152 this is not an "issue" so to say. Upgrade Packages have multiple options and also are sometimes associated with multiple units. This it might lead to Units having upgrade package sections that can't be used. So its not an issue but more due to how upgrade packages are constructed currently.

Thus, I'm closing this ticket.
