### ISSUE TITLE
Feudal Guard - Army Issues

### ISSUE THREAD

**Issue by JamJar152** [schnick3rs/opr-web-companion#60]
Feudal Guardsman - Weapons team upgrade incomplete

![image](https://user-images.githubusercontent.com/93403931/140183467-c3ea86c3-244e-4587-b207-4c36265a9ba8.png)

Feudal Engineers - Weapons team upgrade incomplete

![image](https://user-images.githubusercontent.com/93403931/140183886-51715352-5a40-4a0d-8983-f5b538dc2252.png)

Feudal Specialists - "Replace one Rifle + CCW" and "Replace one Pistol" options are unusable, as the default equipment name is "Plasma Rifles" and there is no way to choose either Rifle or Pistol to enable the options to work.

![image](https://user-images.githubusercontent.com/93403931/140184641-8c0dd901-3ed3-4e0f-8312-2132ca15fa73.png)

Weapon Teams - Weapons team upgrade incomplete

![image](https://user-images.githubusercontent.com/93403931/140184826-0692eac9-ad11-4042-8008-bec4c9620533.png)

**Comment by schnick3rs** [comment]
@JamJar152 weapon teams should now work correctly. Can you verify?

Also, the unreachable option is the same reason described in #59

**Comment by JamJar152** [comment]
Yep, the weapons team upgrades work correctly, cheers

**Comment by schnick3rs** [comment]
Ok, I'm closing this then. @JamJar152 FYI.
