### ISSUE TITLE
Fix Squad Attachments data

### ISSUE THREAD

**Issue by Darguth** [schnick3rs/opr-web-companion#61]
AF now supports the HDF squad attachments format, but we need to clean up the source data.
- [ ] Remove the extraneous upgrade (red) from the HDF upgrade list.
- [ ] Make the Squad Attachment upgrade lists in the Feudal Guard, Soul-Snatcher Cults and Infected Colonies lists mimic the working HDF list (green).

![image](https://user-images.githubusercontent.com/8975633/140194809-d2e161b4-c313-4c56-b389-6a75cc0cd052.png)

**Comment by schnick3rs** [comment]
I think those are fixed now. can you verify @Darguth ?

**Comment by schnick3rs** [comment]
I'm closing this. @Darguth FYI.
