### ISSUE TITLE
Dwarf Guilds upgrades have brackets going to the next line

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#66]
Link: https://opr-list-bui-feature-po-r8wmtp.herokuapp.com/army-books/view/fk1mkbp8apvltu0z/print

![image](https://user-images.githubusercontent.com/58227331/140669328-449f000c-5f15-40b4-acfb-ed85ccad9b54.png)

**Comment by schnick3rs** [comment]
@onepageanon would this work for you 
![image](https://user-images.githubusercontent.com/17150506/140783499-8823c53a-3e08-4ee3-978d-6620ea31555c.png)
