### ISSUE TITLE
PDF View: Space above/below picture

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#71]
Can we get like 1-2 blank spaces above and below the picture, so that it has some room to breathe and isn't cramped by the text?

![image](https://user-images.githubusercontent.com/58227331/141480109-fb4a3dba-a727-4f9c-ba8e-9579e1574bdb.png)

**Comment by schnick3rs** [comment]
Fixed

**Comment by onepageanon** [comment]
Seems to have a space below now, but not above still.

![image](https://user-images.githubusercontent.com/58227331/141832772-f31da5be-59ec-44d3-9383-9f6dff416cf3.png)
