### ISSUE TITLE
Weapon names that end in "s" in the army creator don't have their final "s" in PDF view

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#74]
https://webapp.onepagerules.com/army-books/view/7i7blhft75q9zfdc/print
https://webapp.onepagerules.com/api/army-books/7i7blhft75q9zfdc

Example: HEF Wraith Plane - Distortion Gun**s**

**Comment by schnick3rs** [comment]
@onepageanon values are now better displayed and pluralized
