### ISSUE TITLE
Formatting issue with upgrade options containing more than 1 weapon

### ISSUE THREAD

**Issue by Darguth** [schnick3rs/opr-web-companion#8]
The weapons should either be separated by comma or "and", but not both.

![image](https://user-images.githubusercontent.com/8975633/135903584-fe118f54-6220-41bc-a21d-0c9c52bdd9f3.png)

**Comment by schnick3rs** [comment]
Fixed: https://opr-list-bui-feature-po-r8wmtp.herokuapp.com/army-books/view/fk1mkbp8apvltu0z/print
