### ISSUE TITLE
v2.14 Special Rules Text Changes

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#81]
- Aircraft: This model doesn’t physically interact with other models and terrain, can’t seize objectives, and can’t be moved into contact with. Units targeting aircraft get -12” range and -1 to hit rolls. When activated, this model must always move 18”-36” in a straight line (without turning), and if it goes off-table, then its activation ends, and it must be placed on any table edge again.
- Ambush: This model may be kept in reserve instead of deploying. At the start of any round after the first, you may place the model anywhere, over 9” away from enemy units. If both player have Ambush, they roll-off to see who deploys first, and then alternate in placing them.
- Blast(X): Ignores cover and multiplies hits by X, but can’t deal more hits than models in the target unit.
- Deadly(X): Assign each wound to one model, and multiply it by X.  Note that these wounds don't carry over to other models if the target is killed.
- Fast: Move 9” when using Advance, and 18” when using Rush/Charge.
- Fear: Always counts as having dealt +D3 wounds when checking who won melee.
- Flying: May move through all obstacles, and may ignore terrain effects.
- Hero: May be deployed as part of one friendly unit, which may use its Quality value for morale tests. When taking hits, you must use the unit’s Defense value, until all non-hero models are killed.
- Immobile: May only use Hold actions.
- Impact(X): Deals X melee hits when charging (must be in striking range).
- Indirect: May target enemies that are not in line of sight, and ignores cover from sight obstructions, but gets -1 to hit rolls when shooting after moving.
- Lock-On: Ignores all negative modifiers to hit rolls and range.
- Poison: Unmodified results of 6 to hit are multiplied by 3.
- Psychic(X): May cast one spell during its activation, at any point before attacking. Pick a spell and a target in line of sight, and roll D6+X. If the result is equal or higher than the number in brackets, you may resolve the effects. Enemy psychics within 18” and line of sight of the caster may roll D6+X at the same time, and if the result is higher the spell is blocked. Psychics may only either try to cast or try to block a spell each round.
- Rending: Unmodified results of 6 to hit count as having AP(4), and ignore the regeneration rule.
- Scout: This model may be deployed after all other units, and may then move by up to 12”, ignoring terrain. If both of the players have Scout, they roll-off to see who deploys first, and then alternate in placing and moving them.
- Slow: Move 4” when using Advance, and 8” when using Rush/Charge.
- Sniper: Shoots at Quality 2+, and may pick one model in a unit as its target, which is resolved as if it’s a unit of 1.
- Stealth: Enemies get -1 to hit rolls when shooting at this unit.
- Tough(X): This model must take X wounds before being killed. If a model with tough joins a unit without it, then it is removed last when the unit takes wounds. Note that you must continue to put wounds on the tough model with most wounds in the unit until it is killed, before starting to put them on the next tough model (heroes must be assigned wounds last).
- Transport(X): May transport up to X other models. Units embark by moving into contact, and may use any action to disembark, but only move by up to 6”. Units may also be deployed inside of a transport. If a unit is inside a transport when it is destroyed, then it takes a dangerous terrain test, is immediately Pinned, and surviving models must be placed within 6” of the transport before it is removed.

**Comment by schnick3rs** [comment]
@onepageanon changes prepared.

**Comment by schnick3rs** [comment]
Done
